Default: &defaults
  database: testOnloadError.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: testOnloadError_test.sqlite3
  <<: *defaults

Staging:
  database: testOnloadError_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: testOnloadError_production.sqlite3
  poolsize: 100
  <<: *defaults